### ISSUE TITLE
HtmlNode Attributes.Remove() throws InvalidOperationException

### ISSUE THREAD

**Issue by wanton7** [zzzprojects/html-agility-pack#226]
Currently I have to use workaround below because .Remove() without parameters crashes
`for (int i = node.Attributes.Count - 1; i >= 0; i--)
  node.Attributes.RemoveAt(i);`

```System.InvalidOperationException
  HResult=0x80131509
  Message=Collection was modified; enumeration operation may not execute.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at HtmlAgilityPack.HtmlAttributeCollection.Remove()
```

**Comment by wanton7** [comment]
Not `div.Attributes[0].Remove()` but `div.Attributes.Remove()` to remove all attributes.

**Comment by JonathanMagnan** [comment]
Still working on our side ;(

```csharp
var html = @"<div data-value1='value1' data-value2='value2'>zzz</div>";

var doc = new HtmlAgilityPack.HtmlDocument();
doc.LoadHtml(html);

var div = doc.DocumentNode.SelectSingleNode("//div");
var attribute = div.Attributes.Count;
//// div.Attributes.Remove(div.Attributes[0]);
//div.Attributes[0].Remove();
div.Attributes.Remove();
```

**Comment by wanton7** [comment]
Just noticed that our software is using old 1.4.9.5 version, my bad :) It's probably problem in that older version. But i'll do a repro with 1.4.9.5 and see if it still crashes in 1.8.5.

**Comment by wanton7** [comment]
Yes it crashes in version 1.4.9.5 but not in 1.8.5. Sorry for the trouble!
