### ISSUE TITLE
ArgumentOutOfRangeException when calling  RemoveChild with keepGrandChildren=true

### ISSUE THREAD

**Issue by tipa** [zzzprojects/html-agility-pack#418]
### Description
I need to remove tags that are not supported by my application, but I want to keep the children of those unsupported tags. I go through the tree recursively and call `node.RemoveChild(child, true)` - in some cases this causes an `ArgumentOutOfRangeException` 

### Exception
Exception message: 
```
Node "<p></p>" was not found in the collection
Parameter name: node
```
Stack trace:
```
at HtmlAgilityPack.HtmlNodeCollection.get_Item(HtmlNode node) in D:\html-agility-pack\src\HtmlAgilityPack.Shared\HtmlNodeCollection.cs:line 50
at HtmlAgilityPack.HtmlNode.InsertAfter(HtmlNode newChild, HtmlNode refChild) in D:\html-agility-pack\src\HtmlAgilityPack.Shared\HtmlNode.cs:line 1484
at HtmlAgilityPack.HtmlNode.RemoveChild(HtmlNode oldChild, Boolean keepGrandChildren) in D:\html-agility-pack\src\HtmlAgilityPack.Shared\HtmlNode.cs:line 1702
```   

### Fiddle or Project
https://dotnetfiddle.net/Xuz1TU
```
static string[] SupportedTags = {"#document", "#text", "p", "ul", "ol", "li", "strong", "em", "s", "u", "a"};
public static void Main()
{
	var html = ""; // see text in file attached below
	var doc = new HtmlDocument();
	doc.LoadHtml(html);
	html = FixHtml(html);
	System.Console.WriteLine(html);
}

static string FixHtml(string html)
{
	var doc = new HtmlDocument();
	doc.LoadHtml(html);
	CleanNode(doc.DocumentNode);
	return doc.DocumentNode.InnerHtml;
}

static void CleanNode(HtmlNode parentNode)
{
	for (int i = 0; i < parentNode.ChildNodes.Count; i++)
	{
		var node = parentNode.ChildNodes[i];
		if (!SupportedTags.Contains(node.Name))
		{
			parentNode.RemoveChild(node, true);
			i--;
		}

		CleanNode(node);
	}
}
```
html: [test2.zip](https://github.com/zzzprojects/html-agility-pack/files/5693750/test2.zip)

**Comment by tipa** [comment]
Seems like this was just a code logic error by myself. After changing the code to this, there's no more exceptions:
```
static void CleanNode(HtmlNode parentNode)
{
    for (int i = 0; i < parentNode.ChildNodes.Count; i++)
    {
        var node = parentNode.ChildNodes[i];
        if (!SupportedTags.Contains(node.Name))
        {
            parentNode.RemoveChild(node, true);
            i--;
        }
        else { CleanNode(node); }
    }
}
```
Sorry for the false alarm!
