### ISSUE TITLE
HtmlNode.GetEncapsulatedData fails when target property is a nullable value type

### ISSUE THREAD

**Issue by elgonzo** [zzzprojects/html-agility-pack#510]
## 1. Description

HtmlNode.GetEncapsulatedData throws an exception when properties of some nullable value type should be populated.

## 2. Exception
```
Unhandled exception. System.Exception: Unhandled Exception : Invalid cast from 'System.String' to 'System.Nullable`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
   at HtmlAgilityPack.HtmlNode.GetEncapsulatedData(Type targetType, HtmlDocument htmlDocument) in C:\Repos\HtmlAgilityPack\HtmlAgilityPack.Shared\HtmlNode.Encapsulator.cs:line 224
   at HtmlAgilityPack.HtmlNode.GetEncapsulatedData[T]() in C:\Repos\HtmlAgilityPack\HtmlAgilityPack.Shared\HtmlNode.Encapsulator.cs:line 36
```

## 3. Fiddle or Project

https://dotnetfiddle.net/6JUCcn

```C#
[HasXPath]
public class Model
{
    [XPath("div", "foo")]
    public int? NullableInt {get;set;}
}

					
string html = @"<div foo=""42"">Hello world!</div>";
		
var doc = new HtmlDocument();
doc.LoadHtml(html);
var m = doc.DocumentNode.GetEncapsulatedData<Model>();
		
Console.WriteLine($"m.NullableInt = {m.NullableInt}");
```

## 4. Any further technical details

HAP 1.11.50
.NET 7
(as per dotnetfiddle demo linked above)

**Comment by elgonzo** [comment]
The problem are the calls of `Convert.ChangeType`. According to Github code search, only the HtmlNode.Encapsulator.cs source file features Convert.ChangeType calls: https://github.com/search?q=repo%3Azzzprojects%2Fhtml-agility-pack%20Convert.ChangeType&type=code

To properly support nullable value types, calls of Convert.ChangeType could be replaced with a utility function similar to this:
```C#
static object ChangeType(string value, Type targetType)
{
    var nullableUnderlyingValueType = Nullable.GetUnderlyingType(targetType);
    if (nullableUnderlyingValueType == null)
    {
        return Convert.ChangeType(value, targetType);
    }

    var valueInstance = Convert.ChangeType(value, nullableUnderlyingValueType);
    return Activator.CreateInstance(targetType, valueInstance);
}
```

**Comment by rwecho** [comment]
Additionally, I'm not sure if this is a major feature. Apart from the three places where I have seen type conversions so far, are there any other areas involved? Will it potentially affect more people since the project has not enabled the Nullable project option? 

Also, some of our files are encoded in Windows-1252. Every time I make changes, to avoid disrupting others' work, I save them back as Windows-1252. This seems to be a specific encoding that certain editors use for saving files, right? It that correct to keep Windows-1252 or should we switch to UTF-8 with BOM?

**Comment by elgonzo** [comment]
> Will it potentially affect more people since the project has not enabled the Nullable project option?

The `<nullable>` setting in .csproj project files (and the equivalent `#nullable` pragma) is about nullable **reference** types only. It is not about nullable value types and therefore has no impact on nor is it an indication of whether a project can or does use nullable value types.
